# Generated by Django 5.2 on 2025-04-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0002_preguntatecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='inspeccion.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspeccion.area'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspeccion.division'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspeccion.zona'),
        ),
        migrations.AddField(
            model_name='zona',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='inspeccion.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntatecnica',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='inspeccion.categoria'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inspeccion.owner'),
        ),
    ]
