# Generated by Django 5.2 on 2025-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0003_owner_area_division_equipo_area_equipo_division_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntatecnica',
            options={'ordering': ('categoria__nombre', 'orden', 'descripcion')},
        ),
        migrations.AddField(
            model_name='preguntatecnica',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntatecnica',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='preguntatecnica',
            unique_together={('categoria', 'orden')},
        ),
    ]
