# Generated by Django 5.2 on 2026-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0004_alter_preguntatecnica_options_preguntatecnica_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecciontecnico',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
