# Generated by Django 5.2 on 2026-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0005_inspecciontecnico_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecciontecnico',
            name='es_critico',
            field=models.BooleanField(default=False),
        ),
    ]
