# Generated by Django 5.2 on 2026-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0006_inspecciontecnico_es_critico'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
