# Generated by Django 5.2 on 2026-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0007_inspeccion_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de inicio de la semana (Lunes)')),
                ('asociado', models.CharField(max_length=150)),
                ('equipo', models.CharField(max_length=150)),
                ('zona', models.CharField(blank=True, max_length=150, null=True)),
                ('asignado_por', models.CharField(default='Admin', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asociado', 'zona', 'equipo'],
                'unique_together': {('fecha', 'asociado', 'equipo')},
            },
        ),
    ]
