# Generated by Django 5.2 on 2026-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0008_asignacioninspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='comentario_hallazgo',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de SAP'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sap_equnr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Equipo SAP'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sap_equnr_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Asociado en SAP'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sap_puesto_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puesto de Trabajo SAP'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sap_tplnr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación Técnica (TPLNR)'),
        ),
    ]
