# Generated by Django 5.2 on 2026-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0009_inspeccion_comentario_hallazgo_inspeccion_sap_equnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='sap_nr_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Notificación SAP (NR)'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='sap_nr_status',
            field=models.CharField(blank=True, choices=[('creada', 'Creada en SAP'), ('error', 'Error SAP'), ('pendiente', 'Pendiente')], max_length=20, null=True, verbose_name='Estado sincronización SAP'),
        ),
    ]
