# Generated by Django 5.2 on 2026-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0011_equiposinqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sap_equnr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Equipo SAP (EQUNR)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sap_equnr_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Equipo SAP'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sap_tplnr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación Técnica SAP (TPLNR)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sap_tplnr_desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Ubicación Técnica SAP'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='sap_nr_status',
            field=models.CharField(blank=True, choices=[('creada', 'Creada en SAP'), ('error', 'Error SAP'), ('pendiente', 'Pendiente'), ('cerrada', 'Cerrada en SAP')], max_length=20, null=True, verbose_name='Estado sincronización SAP'),
        ),
    ]
